apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-secure-app-deployment
  labels:
    app: my-secure-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-secure-app
  template:
    metadata:
      labels:
        app: my-secure-app
    spec:
      containers:
      - name: my-secure-app
        image: my-secure-app:latest # The image name from the CI pipeline
        ports:
        - containerPort: 8080
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              # This name must match the name of your Secret
              name: my-api-secret
              key: API_KEY